### ISSUE TITLE
Fix UrlPreviewCommand when run in query

### ISSUE THREAD

**Issue by crisidev** [crisidev/holysee#10]
UrlPreview sends to all transports when done in query.

**Comment by uovobw** [comment]
is this still relevant?

**Comment by crisidev** [comment]
I think so..

**Comment by uovobw** [comment]
i feel like this issue is actually a non-issue, why oh why would anyone send a link to the bot in query? i'm optimist we could close this one...

**Comment by crisidev** [comment]
Fair enough.. I am gonna close this. Let's see if it becomes relevant in the future.
