### ISSUE TITLE
Nickname substitution must only happen inside a non-link string

### ISSUE THREAD

**Issue by uovobw** [crisidev/holysee#15]
This is a tricky one, when a link is sent from either transport, like

https://somehost.com/~username/page

if username happens to be configured in the list of translatable usernames, let's say as ANOTHER, we wil get the link on the other transport as:

https://somehost.com/~@ANOTHER/page

**Comment by crisidev** [comment]
Ah, this is a good one. Cinzia is suggesting to catch the spaces before and after the nick instead of just it.. it could work I think..

**Comment by uovobw** [comment]
i triaged this one a little more, the nickname conversion is already in the `relay` command, so i think the capture with spaces could be the right approach. I would modify the regexp to be able to catch:

- @nickname
- nickname:

this should catch the cases where the nickname is mentioned in either telegram or irc. Catching also the beginning of the line can be overkill, as sometimes the user can be metioned in the middle of a sentence: "today i told @nickname the thing" and this would need to be translated.
Finally, the case

- <space>nickname<space>

can either be captured with optional spaces, and it would translate the link in the description, or without spaces, thus not converting a nickname simply mentioned in passing on irc.

Personally, i think it would be best to only catch cases in which we are _sure_ of the conversion.

**Comment by crisidev** [comment]
Yeah, it think this is a good approach.. it should cover most usecases and we can improve it further in the future

**Comment by uovobw** [comment]
https://github.com/crisidev/holysee/pull/21 is submitted to address this
